fix no value on control when control defined in another file then rule reloads (on another file)
wirenboard/wb-rules pull request #38
Opened 2020-08-21 13:40 UTC by wierdbytes

После PR#16 wbgo

Report: https://support.wirenboard.com/t/novaya-versiya-dvizhka-pravil/4196/92

2020-08-23 21:10 UTC, evgeny-boger commented on wbrules/engine.go
> +				return errGet
а как это вообще работает? 
1) Почему тут IncompleteControlError? Канал же определён
2) Почему правомерно использовать val, если GetValue() вернул ошибку?
3) В каких ещё случаях может быть IncompleteControlError?

2020-08-23 21:10 UTC, evgeny-boger requested changes
а как это вообще работает? 
1) Почему тут IncompleteControlError? Канал же определён
2) Почему правомерно использовать val, если GetValue() вернул ошибку?
3) В каких ещё случаях может быть IncompleteControlError?

2020-08-26 12:00 UTC, wierdbytes commented
1. В случае, если контрол содержит строковое значение и это значение равняется пустой строке (либо значение никогда не выставлялось, либо оно выставлено пользователем пустой строкой) GetValue() возвращает эту ошибку.

1. В wbgo при этой ошибке возвращается "значение по умолчанию" (см. PR#16 в wbgo), здесь мы используем это значение.

1. Метод контрола `checkComplete()` в wbgo: если значение type контрола отсутствует или длина строкового представления значения контрола равна нулю.

2021-04-20 16:54 UTC, webconn commented
Идейно решение здесь не совсем подходящее, по правильному нужно правильно отрабатывать пустые значения для типа text (и, возможно, других) на уровне конвенции. Судя по всему, будет исправлено уже в новой конвенции, чтобы не ломать устоявшееся за всё это время поведение. Возможно, с новой конвенцией привычного wb-rules вообще уже не будет, если перейдём на nodejs.

На уровне проблем пользователей это починено в #44.

2021-04-20 16:54 UTC, closed without merging