add trackMqtt description to readme
wirenboard/wb-rules pull request #43
Opened 2021-03-01 16:13 UTC by brainroot

напиши пожалуйста про trackMqtt в README.md в репозитории wb-rules.
Добавил, с примером. Считаю пример нужным, так понятней.

2021-03-01 17:06 UTC, evgeny-boger requested changes
Давай уберём функцию test01, логгирование вставим в самом trackMqtt.

newValue лучше во что-нибудь переименовать, напримеер в message.

Для логгирования лучше использовать format:

```
log.info("name: {}, value: {}".format(name, value))
```

естественно ,проверить потом.

2021-03-03 17:03 UTC, brainroot commented
> Давай уберём функцию test01, логгирование вставим в самом trackMqtt.
Так и сделал. Сам не знаю зачем изначально так написал.
> newValue лучше во что-нибудь переименовать, напримеер в message.
Переименовал. Странно, что "message" подсвечивает
> 
> Для логгирования лучше использовать format:
> 
> ```
> log.info("name: {}, value: {}".format(name, value))
> ```
Ага, сделал.
> естественно ,проверить потом.
Работает:
```
2021-03-03 20:02:41name: /devices/wb-adc/controls/5Vout, value: 5.04
2021-03-03 20:02:41name: /devices/wb-adc/controls/5Vout, value: 5.03
```

2021-03-04 08:14 UTC, webconn commented on debian/changelog
> +wb-rules (2.6.3) stable; urgency=medium
Я думаю, нет смысла поднимать версию из-за изменения в readme, которое всё равно в пакет не попадает

2021-03-04 08:15 UTC, webconn approved these changes

2021-03-07 20:48 UTC, merged