Feature/32894 fix failed status
wirenboard/wb-rules pull request #45
Opened 2021-05-26 23:06 UTC by webconn

* switch to systemd service from initscript (closes #32894)
 * handle order property in defineVirtualDevice (closes #31810)

Мержить после wbgo-private

2021-05-30 20:13 UTC, webconn commented
Сначала мержим #46

2021-05-31 03:00 UTC, evgeny-boger requested changes
а зачем, кстати, два таких разных изменения сделаны в одном PR?

2021-05-31 03:00 UTC, evgeny-boger commented on debian/wb-rules.service
> +[Unit]
В исходном скрипте был Should-Start и он по-моему появился после каких-то плохо воспроизводимых багов и нужен.

2021-05-31 06:49 UTC, webconn commented on debian/wb-rules.service
> +[Unit]
Действительно, добавлю это тоже

2021-05-31 06:58 UTC, webconn commented
Разные изменения, потому что инитскрипт уже очень сильно мешает, не даёт получать нормальную обратную связь при падении, а поддержка `order` запиливалась за полчаса. Не хотелось делать несколько PR из-за этого, всё равно выкатить хочется всё вместе.

2021-05-31 13:10 UTC, webconn commented
Сделал ребейз в #47

2021-05-31 13:10 UTC, closed without merging