Feature/49386 incomplete support for units
wirenboard/wb-rules pull request #74
Opened 2022-08-24 07:40 UTC by rkochkin

Добавил установку units при создании виртуального устройства.
Исправил поломанные тесты после изменения поведения wbgo.so

2022-08-24 12:38 UTC, webconn requested changes
Нужно ещё обновление в README про то, что мы умеем в `title` без локализации для контролов, и в примеры правил там же прописать

2022-08-24 12:38 UTC, webconn commented on wbrules/engine.go
> +			if err := json.Unmarshal([]byte(metaValue), &t); err != nil {
Стоит что-то с этим пустым `if` сделать, это бесконечно странно. Здесь, ниже и выше

2022-08-24 12:38 UTC, webconn commented on wbrules/engine.go
> +	if titleStr, ok := ctrlDef[VDEV_CONTROL_DESCR_PROP_TITLE]; ok {
~~Хотелось бы иметь возможность тут сделать сразу `title` с переводом, и тесты на это.~~

Впрочем, если уж мы закапываем wb-rules, можно пока и не делать

2022-08-25 16:31 UTC, rkochkin commented on wbrules/engine.go
> +			if err := json.Unmarshal([]byte(metaValue), &t); err != nil {
Поправил

2022-08-25 18:01 UTC, rkochkin commented on wbrules/engine.go
> +	if titleStr, ok := ctrlDef[VDEV_CONTROL_DESCR_PROP_TITLE]; ok {
Я бы сделал по необходимости

2022-08-26 09:00 UTC, webconn reviewed
А поддержка units в meta у нас как-то заезжает в остальных репозиториях? (wbgong, private)?

2022-08-26 10:15 UTC, rkochkin commented
> А поддержка units в meta у нас как-то заезжает в остальных репозиториях? (wbgong, private)?

Она там была и раньше. Но в виде топика отдельного топика /meta/units. Он автоматом заехал в /meta
Кстати, как понимаю, для homeui если есть топик /meta с json,  то одиночные топики, например /meta/readonly, игнорируются.

2022-08-26 10:16 UTC, webconn commented
> Кстати, как понимаю, для homeui если есть топик /meta с json, то одиночные топики, например /meta/readonly, игнорируются.

Всё так

2022-08-26 10:17 UTC, webconn approved these changes

2022-08-26 15:50 UTC, merged

2022-11-20 07:00 UTC, ashumkin commented
а что такое `units` и для чего? в README не указано какие значения оно может/должно принимать

2022-11-20 17:33 UTC, evgeny-boger commented
> а что такое `units` и для чего? в README не указано какие значения оно может/должно принимать

https://github.com/wirenboard/conventions