Added source code evaluation
wirenboard/wb-rules pull request #76
Opened 2022-09-07 15:55 UTC by rkochkin

Исправил поведение при обработке скрипта правил, когда лишняя закрывающая фигурная приводила к экранированию кода, следующего за ней.
Исправил возникающую ошибку, когда на последней строки в скрипте правил после комментария не было перевода строки.

2022-09-08 13:15 UTC, KraPete requested changes

2022-09-08 13:15 UTC, KraPete commented on wbrules/escontext.go
> +	if err := ctx.PevalString(src); err != 0 {
Может, `Pcompile`? Оно есть в оригинальном Duckttape

2022-09-08 13:45 UTC, webconn commented on wbrules/escontext.go
> +	if err := ctx.PevalString(src); err != 0 {
Поддерживаю, `eval` же выполнит код, и если синтаксис как-то хитро окажется валидным, будет нехорошо. В `LoadFunctionFromString` дальше делается `compile` и я так понимаю, что его не хватает. Возможно, если запустить `compile` с другими флагами (скомпилировать как eval, а не как функцию), будет получше

2022-09-09 07:50 UTC, rkochkin commented on wbrules/escontext.go
> +	if err := ctx.PevalString(src); err != 0 {
Изменил на Pcompile

2022-09-09 08:36 UTC, webconn commented on wbrules/escontext.go
> +	if err := ctx.PcompileString(0, src); err != 0 {
А `LoadFunctionFromString` не делает то же самое внутри?

2022-09-09 09:08 UTC, rkochkin commented on wbrules/escontext.go
> +	if err := ctx.PcompileString(0, src); err != 0 {
Он запускает Pcompile c флагами  duktape.DUK_COMPILE_FUNCTION, которая как раз игнорирует то, что за закрывающей фигурной скобкой.

2022-09-12 12:09 UTC, webconn commented on wbrules/escontext.go
> +	if err := ctx.PcompileString(0, src); err != 0 {
Надо тут явно тогда прописать флаг

2022-09-12 13:51 UTC, rkochkin commented on wbrules/escontext.go
> +	if err := ctx.PcompileString(0, src); err != 0 {
Прописал DUK_COMPILE_EVAL

2022-09-12 13:52 UTC, webconn approved these changes

2022-09-12 14:09 UTC, merged