Feature/fix failed to convert value
wirenboard/wb-rules pull request #77
Opened 2022-09-12 09:39 UTC by rkochkin

Поправлены тесты после изменения в PR: https://github.com/wirenboard/wbgo-private/pull/33

2022-10-13 15:30 UTC, webconn requested changes

2022-10-13 15:30 UTC, webconn commented on go.mod
> +	github.com/wirenboard/wbgong v0.4.1-0.20221005075716-d6f68dff99f0
После вливания https://github.com/wirenboard/wbgong/pull/11/ надо будет проставить в wbgong тег и поменять тут запись

2022-10-13 15:30 UTC, webconn commented on wbrules/engine.go
> +		if !ctrl.IsDelete() {
Кажется, это уже переименовали, но сюда не доехало

2022-10-13 15:30 UTC, webconn commented on debian/changelog
> +  * Adapted for the new wbgo.so library
Тут надо написать про то, что лишних логов стало меньше

2022-10-13 16:14 UTC, rkochkin commented on wbrules/engine.go
> +		if !ctrl.IsDelete() {
Да, поправил

2022-10-13 17:00 UTC, rkochkin commented on go.mod
> +	github.com/wirenboard/wbgong v0.4.1-0.20221005075716-d6f68dff99f0
Поправил

2022-10-13 17:01 UTC, rkochkin commented on debian/changelog
> +  * Adapted for the new wbgo.so library
Добавил

2022-10-14 05:48 UTC, webconn approved these changes

2022-10-14 07:49 UTC, merged